#!/bin/bash

# CodePipeline Deployment Helper
# This script provides instructions for fixing the pipeline configuration

echo "🚨 CodePipeline Container Build Issue - Solution Guide"
echo "=================================================="
echo ""
echo "❌ PROBLEM:"
echo "   Your container worked when built directly from the demo-container folder,"
echo "   but fails when built through CodePipeline."
echo ""
echo "🔍 ROOT CAUSE:"
echo "   CodePipeline is using the wrong build context directory."
echo "   It's looking for 'nginx' folder but your container is in 'Presentation/demo-container'"
echo ""
echo "✅ SOLUTIONS:"
echo ""
echo "Option 1 - Update Pipeline Parameter (RECOMMENDED):"
echo "   When deploying your pipeline CloudFormation stack, set:"
echo "   ContainerPath = 'Presentation/demo-container'"
echo ""
echo "Option 2 - Use the new buildspec.yml:"
echo "   A buildspec.yml file has been created in this directory."
echo "   Your pipeline can now build directly from the correct location."
echo ""
echo "Option 3 - Check your current pipeline configuration:"
echo "   aws cloudformation describe-stacks --stack-name YOUR-PIPELINE-STACK-NAME"
echo "   Look for the ContainerPath parameter value"
echo ""
echo "🔧 TO FIX RIGHT NOW:"
echo ""
echo "1. Update your pipeline stack with correct ContainerPath:"
echo "   aws cloudformation update-stack \\"
echo "     --stack-name YOUR-PIPELINE-STACK-NAME \\"
echo "     --use-previous-template \\"
echo "     --parameters ParameterKey=ContainerPath,ParameterValue=Presentation/demo-container \\"
echo "                 ParameterKey=GitHubRepo,UsePreviousValue=true \\"
echo "                 ParameterKey=GitHubBranch,UsePreviousValue=true \\"
echo "                 [... other parameters with UsePreviousValue=true]"
echo ""
echo "2. OR, use CodeBuild with the buildspec.yml from this directory"
echo ""
echo "🚀 After fixing, commit and push to trigger a new build:"
echo "   git add ."
echo "   git commit -m 'Fix pipeline build context and add buildspec.yml'"
echo "   git push origin test"
echo ""
echo "📋 VERIFICATION:"
echo "   Check CodeBuild logs for:"
echo "   ✅ 'Contents of container directory' should show your HTML files"
echo "   ✅ 'Dockerfile not found' should NOT appear"  
echo "   ✅ Docker build should complete successfully"
echo ""
