# Add this to your CloudFormation template under Resources:

  # ECS Task Role (separate from execution role)
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - arn:aws:s3:::wepl-mainpage
                  - arn:aws:s3:::wepl-mainpage/*
                  - arn:aws:s3:::wepl-posting-pages
                  - arn:aws:s3:::wepl-posting-pages/*
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ecs-task-role'

# Then modify your ECS Task Definition to include the task role:
# In the ECSTaskDefinition resource, add:
#   TaskRoleArn: !GetAtt ECSTaskRole.Arn
